Functions on the driver should be protected
open-sausages/MinkSelenium2Driver pull request #4
Opened 2019-11-20 05:28 UTC by andrewnicols

There is no need for many of these methods to be private, and in fact it
makes it impossible to extend the driver sensibly if they are.

The visibility features of PHP mean that any function called in a parent
class by a child class where that parent function calls a private method
means that it is impossible to override the private methods.

This means that it is not possible, for example, to apply bug fixes
locally.

Take, for example, the case of https://github.com/silverstripe/MinkFacebookWebDriver/pull/3

I am unable to simply override the `selectOptionOnElement` function in my version of the driver because that function is private. It is called by `selectOption` and `setValue`. PHP's visibility rules mean that those functions, which are defined on the Silverstripe Driver only see the Silverstripe implementation of all private functions. They are entirely unaware and unable to see any extension of those functions in the child class.

2019-11-25 03:02 UTC, andrewnicols commented
Any chance of some movement on this issue? This is massively killing my ability to get Mink working with W3C Facebook right now.

2019-12-14 01:45 UTC, robbieaverill commented
Hi @andrewnicols, this repository is a fork of https://github.com/minkphp/MinkSelenium2Driver. I'd suggest you raise you issue (and/or pull request) with them. We can sync our changes from upstream if needed.

2019-12-14 03:08 UTC, andrewnicols commented
@robbieaverill,

Sorry, but I really don't have time. Because this bug, and several other bugs, have been unaddressed for several weeks I have ended up writing a brand new driver which extends the CoreDriver and has nothing to do with the Mink\Selenium2Driver. The upstream driver is just too buggy - for example the way in which is uses the Syn.js library is flawed and the driver-testsuite is similarly flawed.

2019-12-14 07:22 UTC, robbieaverill commented
Thanks for the reply @andrewnicols, glad you ended up with something that works! Sorry we didn't get to review this sooner.

2019-12-14 07:29 UTC, robbieaverill requested changes
Thanks for the PR, and sorry we didn't respond sooner. I'm going to say no to this PR unfortunately, mainly because I feel that private methods are the concern of the class who defines them (not children), and the decision to make them private should remain with the upstream repository we've forked. You could redefine the private methods in child classes if you wished to re-use them. Thanks again for your contributions!

2019-12-14 07:29 UTC, closed without merging